### ISSUE TITLE
If optional requriement report lab is not installed program dies with error

### ISSUE THREAD

**Issue by ameygat** [nopri/sqliteboy#1]
```
Traceback (most recent call last):
  File "sqliteboy.py", line 1051, in <module>
    0: PDF_TA_LEFT,
NameError: name 'PDF_TA_LEFT' is not defined

```
There is no check if the PDF_TA_* variables are imported or not. Only the import is in try catch. Catch sets the variable reportlab as None but this value is not checked on line 1051 when assigning style_align_pdf variable.

Note: If reportlab is installed this error does not occur.

**Comment by nopri** [comment]
Hello @ameygat,

Thank you very much for reporting this bug! And, sorry for the delayed response. Just found out that I did not receive notification because i was not watching this repository. 

However, i am currently away from my personal computer, but will fix this bug as soon as possible (within this week). 

nop

**Comment by nopri** [comment]
Hello @ameygat,

I have added a commit to fix this bug. Please let me know, or close this issue if this bug has been fixed. 

Thank you very much for your patience. 
nop

**Comment by ameygat** [comment]
Thanks I think that would solve the issue. Thanks.
